[package]
name = "when"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
argh = "0.1.6"
chrono = "0.4.19"
chrono-tz = "0.6.0"
pest = "2.1.3"
pest_derive = "2.1.0"
