name: WASM Build

on: [push]

jobs:
  build-latest:
    name: WASM  on Latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: jetli/wasm-pack-action@v0.3.0
      - name: Build
        run: (cd web/www; npm ci) && make web-dist
